package skyline.platform.repository.model;

public class THrmNewsWithBLOBs extends THrmNews {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_news.news_content
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    private String newsContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_news.news_topTime
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    private byte[] newsToptime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_news.news_content
     *
     * @return the value of t_hrm_news.news_content
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public String getNewsContent() {
        return newsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_news.news_content
     *
     * @param newsContent the value for t_hrm_news.news_content
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public void setNewsContent(String newsContent) {
        this.newsContent = newsContent == null ? null : newsContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_news.news_topTime
     *
     * @return the value of t_hrm_news.news_topTime
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public byte[] getNewsToptime() {
        return newsToptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_news.news_topTime
     *
     * @param newsToptime the value for t_hrm_news.news_topTime
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public void setNewsToptime(byte[] newsToptime) {
        this.newsToptime = newsToptime;
    }
}