package skyline.platform.repository.model;

public class THrmDeptTeam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_dept_team.id_dept
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    private String idDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_dept_team.id_team
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    private String idTeam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_dept_team.name_team
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    private String nameTeam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_dept_team.describe
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_dept_team.category
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    private String category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_dept_team.id_dept
     *
     * @return the value of t_hrm_dept_team.id_dept
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public String getIdDept() {
        return idDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_dept_team.id_dept
     *
     * @param idDept the value for t_hrm_dept_team.id_dept
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public void setIdDept(String idDept) {
        this.idDept = idDept == null ? null : idDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_dept_team.id_team
     *
     * @return the value of t_hrm_dept_team.id_team
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public String getIdTeam() {
        return idTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_dept_team.id_team
     *
     * @param idTeam the value for t_hrm_dept_team.id_team
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public void setIdTeam(String idTeam) {
        this.idTeam = idTeam == null ? null : idTeam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_dept_team.name_team
     *
     * @return the value of t_hrm_dept_team.name_team
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public String getNameTeam() {
        return nameTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_dept_team.name_team
     *
     * @param nameTeam the value for t_hrm_dept_team.name_team
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public void setNameTeam(String nameTeam) {
        this.nameTeam = nameTeam == null ? null : nameTeam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_dept_team.describe
     *
     * @return the value of t_hrm_dept_team.describe
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_dept_team.describe
     *
     * @param describe the value for t_hrm_dept_team.describe
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_dept_team.category
     *
     * @return the value of t_hrm_dept_team.category
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_dept_team.category
     *
     * @param category the value for t_hrm_dept_team.category
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }
}