package skyline.platform.repository.model;

import java.util.ArrayList;
import java.util.List;

public class THrmNewsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hrm_news
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hrm_news
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hrm_news
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public THrmNewsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hrm_news
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNewsTitleIsNull() {
            addCriterion("news_title is null");
            return (Criteria) this;
        }

        public Criteria andNewsTitleIsNotNull() {
            addCriterion("news_title is not null");
            return (Criteria) this;
        }

        public Criteria andNewsTitleEqualTo(String value) {
            addCriterion("news_title =", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleNotEqualTo(String value) {
            addCriterion("news_title <>", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleGreaterThan(String value) {
            addCriterion("news_title >", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleGreaterThanOrEqualTo(String value) {
            addCriterion("news_title >=", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleLessThan(String value) {
            addCriterion("news_title <", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleLessThanOrEqualTo(String value) {
            addCriterion("news_title <=", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleLike(String value) {
            addCriterion("news_title like", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleNotLike(String value) {
            addCriterion("news_title not like", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleIn(List<String> values) {
            addCriterion("news_title in", values, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleNotIn(List<String> values) {
            addCriterion("news_title not in", values, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleBetween(String value1, String value2) {
            addCriterion("news_title between", value1, value2, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleNotBetween(String value1, String value2) {
            addCriterion("news_title not between", value1, value2, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsImgIsNull() {
            addCriterion("news_img is null");
            return (Criteria) this;
        }

        public Criteria andNewsImgIsNotNull() {
            addCriterion("news_img is not null");
            return (Criteria) this;
        }

        public Criteria andNewsImgEqualTo(String value) {
            addCriterion("news_img =", value, "newsImg");
            return (Criteria) this;
        }

        public Criteria andNewsImgNotEqualTo(String value) {
            addCriterion("news_img <>", value, "newsImg");
            return (Criteria) this;
        }

        public Criteria andNewsImgGreaterThan(String value) {
            addCriterion("news_img >", value, "newsImg");
            return (Criteria) this;
        }

        public Criteria andNewsImgGreaterThanOrEqualTo(String value) {
            addCriterion("news_img >=", value, "newsImg");
            return (Criteria) this;
        }

        public Criteria andNewsImgLessThan(String value) {
            addCriterion("news_img <", value, "newsImg");
            return (Criteria) this;
        }

        public Criteria andNewsImgLessThanOrEqualTo(String value) {
            addCriterion("news_img <=", value, "newsImg");
            return (Criteria) this;
        }

        public Criteria andNewsImgLike(String value) {
            addCriterion("news_img like", value, "newsImg");
            return (Criteria) this;
        }

        public Criteria andNewsImgNotLike(String value) {
            addCriterion("news_img not like", value, "newsImg");
            return (Criteria) this;
        }

        public Criteria andNewsImgIn(List<String> values) {
            addCriterion("news_img in", values, "newsImg");
            return (Criteria) this;
        }

        public Criteria andNewsImgNotIn(List<String> values) {
            addCriterion("news_img not in", values, "newsImg");
            return (Criteria) this;
        }

        public Criteria andNewsImgBetween(String value1, String value2) {
            addCriterion("news_img between", value1, value2, "newsImg");
            return (Criteria) this;
        }

        public Criteria andNewsImgNotBetween(String value1, String value2) {
            addCriterion("news_img not between", value1, value2, "newsImg");
            return (Criteria) this;
        }

        public Criteria andNewsImgFlagIsNull() {
            addCriterion("news_img_flag is null");
            return (Criteria) this;
        }

        public Criteria andNewsImgFlagIsNotNull() {
            addCriterion("news_img_flag is not null");
            return (Criteria) this;
        }

        public Criteria andNewsImgFlagEqualTo(String value) {
            addCriterion("news_img_flag =", value, "newsImgFlag");
            return (Criteria) this;
        }

        public Criteria andNewsImgFlagNotEqualTo(String value) {
            addCriterion("news_img_flag <>", value, "newsImgFlag");
            return (Criteria) this;
        }

        public Criteria andNewsImgFlagGreaterThan(String value) {
            addCriterion("news_img_flag >", value, "newsImgFlag");
            return (Criteria) this;
        }

        public Criteria andNewsImgFlagGreaterThanOrEqualTo(String value) {
            addCriterion("news_img_flag >=", value, "newsImgFlag");
            return (Criteria) this;
        }

        public Criteria andNewsImgFlagLessThan(String value) {
            addCriterion("news_img_flag <", value, "newsImgFlag");
            return (Criteria) this;
        }

        public Criteria andNewsImgFlagLessThanOrEqualTo(String value) {
            addCriterion("news_img_flag <=", value, "newsImgFlag");
            return (Criteria) this;
        }

        public Criteria andNewsImgFlagLike(String value) {
            addCriterion("news_img_flag like", value, "newsImgFlag");
            return (Criteria) this;
        }

        public Criteria andNewsImgFlagNotLike(String value) {
            addCriterion("news_img_flag not like", value, "newsImgFlag");
            return (Criteria) this;
        }

        public Criteria andNewsImgFlagIn(List<String> values) {
            addCriterion("news_img_flag in", values, "newsImgFlag");
            return (Criteria) this;
        }

        public Criteria andNewsImgFlagNotIn(List<String> values) {
            addCriterion("news_img_flag not in", values, "newsImgFlag");
            return (Criteria) this;
        }

        public Criteria andNewsImgFlagBetween(String value1, String value2) {
            addCriterion("news_img_flag between", value1, value2, "newsImgFlag");
            return (Criteria) this;
        }

        public Criteria andNewsImgFlagNotBetween(String value1, String value2) {
            addCriterion("news_img_flag not between", value1, value2, "newsImgFlag");
            return (Criteria) this;
        }

        public Criteria andNewsAttachmentIsNull() {
            addCriterion("news_attachment is null");
            return (Criteria) this;
        }

        public Criteria andNewsAttachmentIsNotNull() {
            addCriterion("news_attachment is not null");
            return (Criteria) this;
        }

        public Criteria andNewsAttachmentEqualTo(String value) {
            addCriterion("news_attachment =", value, "newsAttachment");
            return (Criteria) this;
        }

        public Criteria andNewsAttachmentNotEqualTo(String value) {
            addCriterion("news_attachment <>", value, "newsAttachment");
            return (Criteria) this;
        }

        public Criteria andNewsAttachmentGreaterThan(String value) {
            addCriterion("news_attachment >", value, "newsAttachment");
            return (Criteria) this;
        }

        public Criteria andNewsAttachmentGreaterThanOrEqualTo(String value) {
            addCriterion("news_attachment >=", value, "newsAttachment");
            return (Criteria) this;
        }

        public Criteria andNewsAttachmentLessThan(String value) {
            addCriterion("news_attachment <", value, "newsAttachment");
            return (Criteria) this;
        }

        public Criteria andNewsAttachmentLessThanOrEqualTo(String value) {
            addCriterion("news_attachment <=", value, "newsAttachment");
            return (Criteria) this;
        }

        public Criteria andNewsAttachmentLike(String value) {
            addCriterion("news_attachment like", value, "newsAttachment");
            return (Criteria) this;
        }

        public Criteria andNewsAttachmentNotLike(String value) {
            addCriterion("news_attachment not like", value, "newsAttachment");
            return (Criteria) this;
        }

        public Criteria andNewsAttachmentIn(List<String> values) {
            addCriterion("news_attachment in", values, "newsAttachment");
            return (Criteria) this;
        }

        public Criteria andNewsAttachmentNotIn(List<String> values) {
            addCriterion("news_attachment not in", values, "newsAttachment");
            return (Criteria) this;
        }

        public Criteria andNewsAttachmentBetween(String value1, String value2) {
            addCriterion("news_attachment between", value1, value2, "newsAttachment");
            return (Criteria) this;
        }

        public Criteria andNewsAttachmentNotBetween(String value1, String value2) {
            addCriterion("news_attachment not between", value1, value2, "newsAttachment");
            return (Criteria) this;
        }

        public Criteria andModelIdIsNull() {
            addCriterion("model_id is null");
            return (Criteria) this;
        }

        public Criteria andModelIdIsNotNull() {
            addCriterion("model_id is not null");
            return (Criteria) this;
        }

        public Criteria andModelIdEqualTo(String value) {
            addCriterion("model_id =", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotEqualTo(String value) {
            addCriterion("model_id <>", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdGreaterThan(String value) {
            addCriterion("model_id >", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdGreaterThanOrEqualTo(String value) {
            addCriterion("model_id >=", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdLessThan(String value) {
            addCriterion("model_id <", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdLessThanOrEqualTo(String value) {
            addCriterion("model_id <=", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdLike(String value) {
            addCriterion("model_id like", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotLike(String value) {
            addCriterion("model_id not like", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdIn(List<String> values) {
            addCriterion("model_id in", values, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotIn(List<String> values) {
            addCriterion("model_id not in", values, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdBetween(String value1, String value2) {
            addCriterion("model_id between", value1, value2, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotBetween(String value1, String value2) {
            addCriterion("model_id not between", value1, value2, "modelId");
            return (Criteria) this;
        }

        public Criteria andCentralDepartmentIdIsNull() {
            addCriterion("central_department_id is null");
            return (Criteria) this;
        }

        public Criteria andCentralDepartmentIdIsNotNull() {
            addCriterion("central_department_id is not null");
            return (Criteria) this;
        }

        public Criteria andCentralDepartmentIdEqualTo(String value) {
            addCriterion("central_department_id =", value, "centralDepartmentId");
            return (Criteria) this;
        }

        public Criteria andCentralDepartmentIdNotEqualTo(String value) {
            addCriterion("central_department_id <>", value, "centralDepartmentId");
            return (Criteria) this;
        }

        public Criteria andCentralDepartmentIdGreaterThan(String value) {
            addCriterion("central_department_id >", value, "centralDepartmentId");
            return (Criteria) this;
        }

        public Criteria andCentralDepartmentIdGreaterThanOrEqualTo(String value) {
            addCriterion("central_department_id >=", value, "centralDepartmentId");
            return (Criteria) this;
        }

        public Criteria andCentralDepartmentIdLessThan(String value) {
            addCriterion("central_department_id <", value, "centralDepartmentId");
            return (Criteria) this;
        }

        public Criteria andCentralDepartmentIdLessThanOrEqualTo(String value) {
            addCriterion("central_department_id <=", value, "centralDepartmentId");
            return (Criteria) this;
        }

        public Criteria andCentralDepartmentIdLike(String value) {
            addCriterion("central_department_id like", value, "centralDepartmentId");
            return (Criteria) this;
        }

        public Criteria andCentralDepartmentIdNotLike(String value) {
            addCriterion("central_department_id not like", value, "centralDepartmentId");
            return (Criteria) this;
        }

        public Criteria andCentralDepartmentIdIn(List<String> values) {
            addCriterion("central_department_id in", values, "centralDepartmentId");
            return (Criteria) this;
        }

        public Criteria andCentralDepartmentIdNotIn(List<String> values) {
            addCriterion("central_department_id not in", values, "centralDepartmentId");
            return (Criteria) this;
        }

        public Criteria andCentralDepartmentIdBetween(String value1, String value2) {
            addCriterion("central_department_id between", value1, value2, "centralDepartmentId");
            return (Criteria) this;
        }

        public Criteria andCentralDepartmentIdNotBetween(String value1, String value2) {
            addCriterion("central_department_id not between", value1, value2, "centralDepartmentId");
            return (Criteria) this;
        }

        public Criteria andNewsIstopIsNull() {
            addCriterion("news_istop is null");
            return (Criteria) this;
        }

        public Criteria andNewsIstopIsNotNull() {
            addCriterion("news_istop is not null");
            return (Criteria) this;
        }

        public Criteria andNewsIstopEqualTo(String value) {
            addCriterion("news_istop =", value, "newsIstop");
            return (Criteria) this;
        }

        public Criteria andNewsIstopNotEqualTo(String value) {
            addCriterion("news_istop <>", value, "newsIstop");
            return (Criteria) this;
        }

        public Criteria andNewsIstopGreaterThan(String value) {
            addCriterion("news_istop >", value, "newsIstop");
            return (Criteria) this;
        }

        public Criteria andNewsIstopGreaterThanOrEqualTo(String value) {
            addCriterion("news_istop >=", value, "newsIstop");
            return (Criteria) this;
        }

        public Criteria andNewsIstopLessThan(String value) {
            addCriterion("news_istop <", value, "newsIstop");
            return (Criteria) this;
        }

        public Criteria andNewsIstopLessThanOrEqualTo(String value) {
            addCriterion("news_istop <=", value, "newsIstop");
            return (Criteria) this;
        }

        public Criteria andNewsIstopLike(String value) {
            addCriterion("news_istop like", value, "newsIstop");
            return (Criteria) this;
        }

        public Criteria andNewsIstopNotLike(String value) {
            addCriterion("news_istop not like", value, "newsIstop");
            return (Criteria) this;
        }

        public Criteria andNewsIstopIn(List<String> values) {
            addCriterion("news_istop in", values, "newsIstop");
            return (Criteria) this;
        }

        public Criteria andNewsIstopNotIn(List<String> values) {
            addCriterion("news_istop not in", values, "newsIstop");
            return (Criteria) this;
        }

        public Criteria andNewsIstopBetween(String value1, String value2) {
            addCriterion("news_istop between", value1, value2, "newsIstop");
            return (Criteria) this;
        }

        public Criteria andNewsIstopNotBetween(String value1, String value2) {
            addCriterion("news_istop not between", value1, value2, "newsIstop");
            return (Criteria) this;
        }

        public Criteria andIsenableIsNull() {
            addCriterion("isenable is null");
            return (Criteria) this;
        }

        public Criteria andIsenableIsNotNull() {
            addCriterion("isenable is not null");
            return (Criteria) this;
        }

        public Criteria andIsenableEqualTo(String value) {
            addCriterion("isenable =", value, "isenable");
            return (Criteria) this;
        }

        public Criteria andIsenableNotEqualTo(String value) {
            addCriterion("isenable <>", value, "isenable");
            return (Criteria) this;
        }

        public Criteria andIsenableGreaterThan(String value) {
            addCriterion("isenable >", value, "isenable");
            return (Criteria) this;
        }

        public Criteria andIsenableGreaterThanOrEqualTo(String value) {
            addCriterion("isenable >=", value, "isenable");
            return (Criteria) this;
        }

        public Criteria andIsenableLessThan(String value) {
            addCriterion("isenable <", value, "isenable");
            return (Criteria) this;
        }

        public Criteria andIsenableLessThanOrEqualTo(String value) {
            addCriterion("isenable <=", value, "isenable");
            return (Criteria) this;
        }

        public Criteria andIsenableLike(String value) {
            addCriterion("isenable like", value, "isenable");
            return (Criteria) this;
        }

        public Criteria andIsenableNotLike(String value) {
            addCriterion("isenable not like", value, "isenable");
            return (Criteria) this;
        }

        public Criteria andIsenableIn(List<String> values) {
            addCriterion("isenable in", values, "isenable");
            return (Criteria) this;
        }

        public Criteria andIsenableNotIn(List<String> values) {
            addCriterion("isenable not in", values, "isenable");
            return (Criteria) this;
        }

        public Criteria andIsenableBetween(String value1, String value2) {
            addCriterion("isenable between", value1, value2, "isenable");
            return (Criteria) this;
        }

        public Criteria andIsenableNotBetween(String value1, String value2) {
            addCriterion("isenable not between", value1, value2, "isenable");
            return (Criteria) this;
        }

        public Criteria andNewsCreatedtimeIsNull() {
            addCriterion("news_createdTime is null");
            return (Criteria) this;
        }

        public Criteria andNewsCreatedtimeIsNotNull() {
            addCriterion("news_createdTime is not null");
            return (Criteria) this;
        }

        public Criteria andNewsCreatedtimeEqualTo(String value) {
            addCriterion("news_createdTime =", value, "newsCreatedtime");
            return (Criteria) this;
        }

        public Criteria andNewsCreatedtimeNotEqualTo(String value) {
            addCriterion("news_createdTime <>", value, "newsCreatedtime");
            return (Criteria) this;
        }

        public Criteria andNewsCreatedtimeGreaterThan(String value) {
            addCriterion("news_createdTime >", value, "newsCreatedtime");
            return (Criteria) this;
        }

        public Criteria andNewsCreatedtimeGreaterThanOrEqualTo(String value) {
            addCriterion("news_createdTime >=", value, "newsCreatedtime");
            return (Criteria) this;
        }

        public Criteria andNewsCreatedtimeLessThan(String value) {
            addCriterion("news_createdTime <", value, "newsCreatedtime");
            return (Criteria) this;
        }

        public Criteria andNewsCreatedtimeLessThanOrEqualTo(String value) {
            addCriterion("news_createdTime <=", value, "newsCreatedtime");
            return (Criteria) this;
        }

        public Criteria andNewsCreatedtimeLike(String value) {
            addCriterion("news_createdTime like", value, "newsCreatedtime");
            return (Criteria) this;
        }

        public Criteria andNewsCreatedtimeNotLike(String value) {
            addCriterion("news_createdTime not like", value, "newsCreatedtime");
            return (Criteria) this;
        }

        public Criteria andNewsCreatedtimeIn(List<String> values) {
            addCriterion("news_createdTime in", values, "newsCreatedtime");
            return (Criteria) this;
        }

        public Criteria andNewsCreatedtimeNotIn(List<String> values) {
            addCriterion("news_createdTime not in", values, "newsCreatedtime");
            return (Criteria) this;
        }

        public Criteria andNewsCreatedtimeBetween(String value1, String value2) {
            addCriterion("news_createdTime between", value1, value2, "newsCreatedtime");
            return (Criteria) this;
        }

        public Criteria andNewsCreatedtimeNotBetween(String value1, String value2) {
            addCriterion("news_createdTime not between", value1, value2, "newsCreatedtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hrm_news
     *
     * @mbggenerated do_not_delete_during_merge Thu Oct 22 15:53:55 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hrm_news
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}