package skyline.platform.repository.model;

public class THrmStaffPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.ser_no
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String serNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_00
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit00;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_01
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_02
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_03
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit03;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_04
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit04;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_05
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit05;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_06
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit06;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_07
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit07;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_08
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit08;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_09
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit09;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_10
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_11
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_12
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_13
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_14
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_15
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_16
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_17
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_18
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_19
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_20
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_21
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit21;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_22
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit22;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_23
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit23;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_24
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit24;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_25
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_26
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit26;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_27
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit27;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_28
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit28;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_29
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit29;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_30
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit30;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_31
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit31;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_32
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit32;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_33
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit33;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_34
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit34;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_35
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit35;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_36
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit36;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_37
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit37;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_38
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit38;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.permit_39
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String permit39;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_permission.id_machine
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String idMachine;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.ser_no
     *
     * @return the value of t_hrm_staff_permission.ser_no
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getSerNo() {
        return serNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.ser_no
     *
     * @param serNo the value for t_hrm_staff_permission.ser_no
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setSerNo(String serNo) {
        this.serNo = serNo == null ? null : serNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_00
     *
     * @return the value of t_hrm_staff_permission.permit_00
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit00() {
        return permit00;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_00
     *
     * @param permit00 the value for t_hrm_staff_permission.permit_00
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit00(String permit00) {
        this.permit00 = permit00 == null ? null : permit00.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_01
     *
     * @return the value of t_hrm_staff_permission.permit_01
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit01() {
        return permit01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_01
     *
     * @param permit01 the value for t_hrm_staff_permission.permit_01
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit01(String permit01) {
        this.permit01 = permit01 == null ? null : permit01.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_02
     *
     * @return the value of t_hrm_staff_permission.permit_02
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit02() {
        return permit02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_02
     *
     * @param permit02 the value for t_hrm_staff_permission.permit_02
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit02(String permit02) {
        this.permit02 = permit02 == null ? null : permit02.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_03
     *
     * @return the value of t_hrm_staff_permission.permit_03
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit03() {
        return permit03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_03
     *
     * @param permit03 the value for t_hrm_staff_permission.permit_03
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit03(String permit03) {
        this.permit03 = permit03 == null ? null : permit03.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_04
     *
     * @return the value of t_hrm_staff_permission.permit_04
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit04() {
        return permit04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_04
     *
     * @param permit04 the value for t_hrm_staff_permission.permit_04
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit04(String permit04) {
        this.permit04 = permit04 == null ? null : permit04.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_05
     *
     * @return the value of t_hrm_staff_permission.permit_05
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit05() {
        return permit05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_05
     *
     * @param permit05 the value for t_hrm_staff_permission.permit_05
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit05(String permit05) {
        this.permit05 = permit05 == null ? null : permit05.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_06
     *
     * @return the value of t_hrm_staff_permission.permit_06
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit06() {
        return permit06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_06
     *
     * @param permit06 the value for t_hrm_staff_permission.permit_06
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit06(String permit06) {
        this.permit06 = permit06 == null ? null : permit06.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_07
     *
     * @return the value of t_hrm_staff_permission.permit_07
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit07() {
        return permit07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_07
     *
     * @param permit07 the value for t_hrm_staff_permission.permit_07
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit07(String permit07) {
        this.permit07 = permit07 == null ? null : permit07.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_08
     *
     * @return the value of t_hrm_staff_permission.permit_08
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit08() {
        return permit08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_08
     *
     * @param permit08 the value for t_hrm_staff_permission.permit_08
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit08(String permit08) {
        this.permit08 = permit08 == null ? null : permit08.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_09
     *
     * @return the value of t_hrm_staff_permission.permit_09
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit09() {
        return permit09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_09
     *
     * @param permit09 the value for t_hrm_staff_permission.permit_09
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit09(String permit09) {
        this.permit09 = permit09 == null ? null : permit09.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_10
     *
     * @return the value of t_hrm_staff_permission.permit_10
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit10() {
        return permit10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_10
     *
     * @param permit10 the value for t_hrm_staff_permission.permit_10
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit10(String permit10) {
        this.permit10 = permit10 == null ? null : permit10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_11
     *
     * @return the value of t_hrm_staff_permission.permit_11
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit11() {
        return permit11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_11
     *
     * @param permit11 the value for t_hrm_staff_permission.permit_11
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit11(String permit11) {
        this.permit11 = permit11 == null ? null : permit11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_12
     *
     * @return the value of t_hrm_staff_permission.permit_12
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit12() {
        return permit12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_12
     *
     * @param permit12 the value for t_hrm_staff_permission.permit_12
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit12(String permit12) {
        this.permit12 = permit12 == null ? null : permit12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_13
     *
     * @return the value of t_hrm_staff_permission.permit_13
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit13() {
        return permit13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_13
     *
     * @param permit13 the value for t_hrm_staff_permission.permit_13
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit13(String permit13) {
        this.permit13 = permit13 == null ? null : permit13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_14
     *
     * @return the value of t_hrm_staff_permission.permit_14
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit14() {
        return permit14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_14
     *
     * @param permit14 the value for t_hrm_staff_permission.permit_14
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit14(String permit14) {
        this.permit14 = permit14 == null ? null : permit14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_15
     *
     * @return the value of t_hrm_staff_permission.permit_15
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit15() {
        return permit15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_15
     *
     * @param permit15 the value for t_hrm_staff_permission.permit_15
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit15(String permit15) {
        this.permit15 = permit15 == null ? null : permit15.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_16
     *
     * @return the value of t_hrm_staff_permission.permit_16
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit16() {
        return permit16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_16
     *
     * @param permit16 the value for t_hrm_staff_permission.permit_16
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit16(String permit16) {
        this.permit16 = permit16 == null ? null : permit16.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_17
     *
     * @return the value of t_hrm_staff_permission.permit_17
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit17() {
        return permit17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_17
     *
     * @param permit17 the value for t_hrm_staff_permission.permit_17
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit17(String permit17) {
        this.permit17 = permit17 == null ? null : permit17.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_18
     *
     * @return the value of t_hrm_staff_permission.permit_18
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit18() {
        return permit18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_18
     *
     * @param permit18 the value for t_hrm_staff_permission.permit_18
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit18(String permit18) {
        this.permit18 = permit18 == null ? null : permit18.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_19
     *
     * @return the value of t_hrm_staff_permission.permit_19
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit19() {
        return permit19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_19
     *
     * @param permit19 the value for t_hrm_staff_permission.permit_19
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit19(String permit19) {
        this.permit19 = permit19 == null ? null : permit19.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_20
     *
     * @return the value of t_hrm_staff_permission.permit_20
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit20() {
        return permit20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_20
     *
     * @param permit20 the value for t_hrm_staff_permission.permit_20
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit20(String permit20) {
        this.permit20 = permit20 == null ? null : permit20.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_21
     *
     * @return the value of t_hrm_staff_permission.permit_21
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit21() {
        return permit21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_21
     *
     * @param permit21 the value for t_hrm_staff_permission.permit_21
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit21(String permit21) {
        this.permit21 = permit21 == null ? null : permit21.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_22
     *
     * @return the value of t_hrm_staff_permission.permit_22
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit22() {
        return permit22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_22
     *
     * @param permit22 the value for t_hrm_staff_permission.permit_22
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit22(String permit22) {
        this.permit22 = permit22 == null ? null : permit22.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_23
     *
     * @return the value of t_hrm_staff_permission.permit_23
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit23() {
        return permit23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_23
     *
     * @param permit23 the value for t_hrm_staff_permission.permit_23
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit23(String permit23) {
        this.permit23 = permit23 == null ? null : permit23.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_24
     *
     * @return the value of t_hrm_staff_permission.permit_24
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit24() {
        return permit24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_24
     *
     * @param permit24 the value for t_hrm_staff_permission.permit_24
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit24(String permit24) {
        this.permit24 = permit24 == null ? null : permit24.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_25
     *
     * @return the value of t_hrm_staff_permission.permit_25
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit25() {
        return permit25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_25
     *
     * @param permit25 the value for t_hrm_staff_permission.permit_25
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit25(String permit25) {
        this.permit25 = permit25 == null ? null : permit25.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_26
     *
     * @return the value of t_hrm_staff_permission.permit_26
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit26() {
        return permit26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_26
     *
     * @param permit26 the value for t_hrm_staff_permission.permit_26
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit26(String permit26) {
        this.permit26 = permit26 == null ? null : permit26.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_27
     *
     * @return the value of t_hrm_staff_permission.permit_27
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit27() {
        return permit27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_27
     *
     * @param permit27 the value for t_hrm_staff_permission.permit_27
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit27(String permit27) {
        this.permit27 = permit27 == null ? null : permit27.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_28
     *
     * @return the value of t_hrm_staff_permission.permit_28
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit28() {
        return permit28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_28
     *
     * @param permit28 the value for t_hrm_staff_permission.permit_28
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit28(String permit28) {
        this.permit28 = permit28 == null ? null : permit28.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_29
     *
     * @return the value of t_hrm_staff_permission.permit_29
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit29() {
        return permit29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_29
     *
     * @param permit29 the value for t_hrm_staff_permission.permit_29
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit29(String permit29) {
        this.permit29 = permit29 == null ? null : permit29.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_30
     *
     * @return the value of t_hrm_staff_permission.permit_30
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit30() {
        return permit30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_30
     *
     * @param permit30 the value for t_hrm_staff_permission.permit_30
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit30(String permit30) {
        this.permit30 = permit30 == null ? null : permit30.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_31
     *
     * @return the value of t_hrm_staff_permission.permit_31
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit31() {
        return permit31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_31
     *
     * @param permit31 the value for t_hrm_staff_permission.permit_31
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit31(String permit31) {
        this.permit31 = permit31 == null ? null : permit31.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_32
     *
     * @return the value of t_hrm_staff_permission.permit_32
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit32() {
        return permit32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_32
     *
     * @param permit32 the value for t_hrm_staff_permission.permit_32
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit32(String permit32) {
        this.permit32 = permit32 == null ? null : permit32.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_33
     *
     * @return the value of t_hrm_staff_permission.permit_33
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit33() {
        return permit33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_33
     *
     * @param permit33 the value for t_hrm_staff_permission.permit_33
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit33(String permit33) {
        this.permit33 = permit33 == null ? null : permit33.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_34
     *
     * @return the value of t_hrm_staff_permission.permit_34
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit34() {
        return permit34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_34
     *
     * @param permit34 the value for t_hrm_staff_permission.permit_34
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit34(String permit34) {
        this.permit34 = permit34 == null ? null : permit34.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_35
     *
     * @return the value of t_hrm_staff_permission.permit_35
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit35() {
        return permit35;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_35
     *
     * @param permit35 the value for t_hrm_staff_permission.permit_35
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit35(String permit35) {
        this.permit35 = permit35 == null ? null : permit35.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_36
     *
     * @return the value of t_hrm_staff_permission.permit_36
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit36() {
        return permit36;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_36
     *
     * @param permit36 the value for t_hrm_staff_permission.permit_36
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit36(String permit36) {
        this.permit36 = permit36 == null ? null : permit36.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_37
     *
     * @return the value of t_hrm_staff_permission.permit_37
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit37() {
        return permit37;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_37
     *
     * @param permit37 the value for t_hrm_staff_permission.permit_37
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit37(String permit37) {
        this.permit37 = permit37 == null ? null : permit37.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_38
     *
     * @return the value of t_hrm_staff_permission.permit_38
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit38() {
        return permit38;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_38
     *
     * @param permit38 the value for t_hrm_staff_permission.permit_38
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit38(String permit38) {
        this.permit38 = permit38 == null ? null : permit38.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.permit_39
     *
     * @return the value of t_hrm_staff_permission.permit_39
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getPermit39() {
        return permit39;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.permit_39
     *
     * @param permit39 the value for t_hrm_staff_permission.permit_39
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setPermit39(String permit39) {
        this.permit39 = permit39 == null ? null : permit39.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_permission.id_machine
     *
     * @return the value of t_hrm_staff_permission.id_machine
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getIdMachine() {
        return idMachine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_permission.id_machine
     *
     * @param idMachine the value for t_hrm_staff_permission.id_machine
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setIdMachine(String idMachine) {
        this.idMachine = idMachine == null ? null : idMachine.trim();
    }
}