package skyline.platform.repository.model;

import java.util.ArrayList;
import java.util.List;

public class THrmStaffBaseInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public THrmStaffBaseInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSerNoIsNull() {
            addCriterion("ser_no is null");
            return (Criteria) this;
        }

        public Criteria andSerNoIsNotNull() {
            addCriterion("ser_no is not null");
            return (Criteria) this;
        }

        public Criteria andSerNoEqualTo(String value) {
            addCriterion("ser_no =", value, "serNo");
            return (Criteria) this;
        }

        public Criteria andSerNoNotEqualTo(String value) {
            addCriterion("ser_no <>", value, "serNo");
            return (Criteria) this;
        }

        public Criteria andSerNoGreaterThan(String value) {
            addCriterion("ser_no >", value, "serNo");
            return (Criteria) this;
        }

        public Criteria andSerNoGreaterThanOrEqualTo(String value) {
            addCriterion("ser_no >=", value, "serNo");
            return (Criteria) this;
        }

        public Criteria andSerNoLessThan(String value) {
            addCriterion("ser_no <", value, "serNo");
            return (Criteria) this;
        }

        public Criteria andSerNoLessThanOrEqualTo(String value) {
            addCriterion("ser_no <=", value, "serNo");
            return (Criteria) this;
        }

        public Criteria andSerNoLike(String value) {
            addCriterion("ser_no like", value, "serNo");
            return (Criteria) this;
        }

        public Criteria andSerNoNotLike(String value) {
            addCriterion("ser_no not like", value, "serNo");
            return (Criteria) this;
        }

        public Criteria andSerNoIn(List<String> values) {
            addCriterion("ser_no in", values, "serNo");
            return (Criteria) this;
        }

        public Criteria andSerNoNotIn(List<String> values) {
            addCriterion("ser_no not in", values, "serNo");
            return (Criteria) this;
        }

        public Criteria andSerNoBetween(String value1, String value2) {
            addCriterion("ser_no between", value1, value2, "serNo");
            return (Criteria) this;
        }

        public Criteria andSerNoNotBetween(String value1, String value2) {
            addCriterion("ser_no not between", value1, value2, "serNo");
            return (Criteria) this;
        }

        public Criteria andSerNameIsNull() {
            addCriterion("ser_name is null");
            return (Criteria) this;
        }

        public Criteria andSerNameIsNotNull() {
            addCriterion("ser_name is not null");
            return (Criteria) this;
        }

        public Criteria andSerNameEqualTo(String value) {
            addCriterion("ser_name =", value, "serName");
            return (Criteria) this;
        }

        public Criteria andSerNameNotEqualTo(String value) {
            addCriterion("ser_name <>", value, "serName");
            return (Criteria) this;
        }

        public Criteria andSerNameGreaterThan(String value) {
            addCriterion("ser_name >", value, "serName");
            return (Criteria) this;
        }

        public Criteria andSerNameGreaterThanOrEqualTo(String value) {
            addCriterion("ser_name >=", value, "serName");
            return (Criteria) this;
        }

        public Criteria andSerNameLessThan(String value) {
            addCriterion("ser_name <", value, "serName");
            return (Criteria) this;
        }

        public Criteria andSerNameLessThanOrEqualTo(String value) {
            addCriterion("ser_name <=", value, "serName");
            return (Criteria) this;
        }

        public Criteria andSerNameLike(String value) {
            addCriterion("ser_name like", value, "serName");
            return (Criteria) this;
        }

        public Criteria andSerNameNotLike(String value) {
            addCriterion("ser_name not like", value, "serName");
            return (Criteria) this;
        }

        public Criteria andSerNameIn(List<String> values) {
            addCriterion("ser_name in", values, "serName");
            return (Criteria) this;
        }

        public Criteria andSerNameNotIn(List<String> values) {
            addCriterion("ser_name not in", values, "serName");
            return (Criteria) this;
        }

        public Criteria andSerNameBetween(String value1, String value2) {
            addCriterion("ser_name between", value1, value2, "serName");
            return (Criteria) this;
        }

        public Criteria andSerNameNotBetween(String value1, String value2) {
            addCriterion("ser_name not between", value1, value2, "serName");
            return (Criteria) this;
        }

        public Criteria andSerPwdIsNull() {
            addCriterion("ser_pwd is null");
            return (Criteria) this;
        }

        public Criteria andSerPwdIsNotNull() {
            addCriterion("ser_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andSerPwdEqualTo(String value) {
            addCriterion("ser_pwd =", value, "serPwd");
            return (Criteria) this;
        }

        public Criteria andSerPwdNotEqualTo(String value) {
            addCriterion("ser_pwd <>", value, "serPwd");
            return (Criteria) this;
        }

        public Criteria andSerPwdGreaterThan(String value) {
            addCriterion("ser_pwd >", value, "serPwd");
            return (Criteria) this;
        }

        public Criteria andSerPwdGreaterThanOrEqualTo(String value) {
            addCriterion("ser_pwd >=", value, "serPwd");
            return (Criteria) this;
        }

        public Criteria andSerPwdLessThan(String value) {
            addCriterion("ser_pwd <", value, "serPwd");
            return (Criteria) this;
        }

        public Criteria andSerPwdLessThanOrEqualTo(String value) {
            addCriterion("ser_pwd <=", value, "serPwd");
            return (Criteria) this;
        }

        public Criteria andSerPwdLike(String value) {
            addCriterion("ser_pwd like", value, "serPwd");
            return (Criteria) this;
        }

        public Criteria andSerPwdNotLike(String value) {
            addCriterion("ser_pwd not like", value, "serPwd");
            return (Criteria) this;
        }

        public Criteria andSerPwdIn(List<String> values) {
            addCriterion("ser_pwd in", values, "serPwd");
            return (Criteria) this;
        }

        public Criteria andSerPwdNotIn(List<String> values) {
            addCriterion("ser_pwd not in", values, "serPwd");
            return (Criteria) this;
        }

        public Criteria andSerPwdBetween(String value1, String value2) {
            addCriterion("ser_pwd between", value1, value2, "serPwd");
            return (Criteria) this;
        }

        public Criteria andSerPwdNotBetween(String value1, String value2) {
            addCriterion("ser_pwd not between", value1, value2, "serPwd");
            return (Criteria) this;
        }

        public Criteria andIdDeptIsNull() {
            addCriterion("id_dept is null");
            return (Criteria) this;
        }

        public Criteria andIdDeptIsNotNull() {
            addCriterion("id_dept is not null");
            return (Criteria) this;
        }

        public Criteria andIdDeptEqualTo(String value) {
            addCriterion("id_dept =", value, "idDept");
            return (Criteria) this;
        }

        public Criteria andIdDeptNotEqualTo(String value) {
            addCriterion("id_dept <>", value, "idDept");
            return (Criteria) this;
        }

        public Criteria andIdDeptGreaterThan(String value) {
            addCriterion("id_dept >", value, "idDept");
            return (Criteria) this;
        }

        public Criteria andIdDeptGreaterThanOrEqualTo(String value) {
            addCriterion("id_dept >=", value, "idDept");
            return (Criteria) this;
        }

        public Criteria andIdDeptLessThan(String value) {
            addCriterion("id_dept <", value, "idDept");
            return (Criteria) this;
        }

        public Criteria andIdDeptLessThanOrEqualTo(String value) {
            addCriterion("id_dept <=", value, "idDept");
            return (Criteria) this;
        }

        public Criteria andIdDeptLike(String value) {
            addCriterion("id_dept like", value, "idDept");
            return (Criteria) this;
        }

        public Criteria andIdDeptNotLike(String value) {
            addCriterion("id_dept not like", value, "idDept");
            return (Criteria) this;
        }

        public Criteria andIdDeptIn(List<String> values) {
            addCriterion("id_dept in", values, "idDept");
            return (Criteria) this;
        }

        public Criteria andIdDeptNotIn(List<String> values) {
            addCriterion("id_dept not in", values, "idDept");
            return (Criteria) this;
        }

        public Criteria andIdDeptBetween(String value1, String value2) {
            addCriterion("id_dept between", value1, value2, "idDept");
            return (Criteria) this;
        }

        public Criteria andIdDeptNotBetween(String value1, String value2) {
            addCriterion("id_dept not between", value1, value2, "idDept");
            return (Criteria) this;
        }

        public Criteria andIdTeamIsNull() {
            addCriterion("id_team is null");
            return (Criteria) this;
        }

        public Criteria andIdTeamIsNotNull() {
            addCriterion("id_team is not null");
            return (Criteria) this;
        }

        public Criteria andIdTeamEqualTo(String value) {
            addCriterion("id_team =", value, "idTeam");
            return (Criteria) this;
        }

        public Criteria andIdTeamNotEqualTo(String value) {
            addCriterion("id_team <>", value, "idTeam");
            return (Criteria) this;
        }

        public Criteria andIdTeamGreaterThan(String value) {
            addCriterion("id_team >", value, "idTeam");
            return (Criteria) this;
        }

        public Criteria andIdTeamGreaterThanOrEqualTo(String value) {
            addCriterion("id_team >=", value, "idTeam");
            return (Criteria) this;
        }

        public Criteria andIdTeamLessThan(String value) {
            addCriterion("id_team <", value, "idTeam");
            return (Criteria) this;
        }

        public Criteria andIdTeamLessThanOrEqualTo(String value) {
            addCriterion("id_team <=", value, "idTeam");
            return (Criteria) this;
        }

        public Criteria andIdTeamLike(String value) {
            addCriterion("id_team like", value, "idTeam");
            return (Criteria) this;
        }

        public Criteria andIdTeamNotLike(String value) {
            addCriterion("id_team not like", value, "idTeam");
            return (Criteria) this;
        }

        public Criteria andIdTeamIn(List<String> values) {
            addCriterion("id_team in", values, "idTeam");
            return (Criteria) this;
        }

        public Criteria andIdTeamNotIn(List<String> values) {
            addCriterion("id_team not in", values, "idTeam");
            return (Criteria) this;
        }

        public Criteria andIdTeamBetween(String value1, String value2) {
            addCriterion("id_team between", value1, value2, "idTeam");
            return (Criteria) this;
        }

        public Criteria andIdTeamNotBetween(String value1, String value2) {
            addCriterion("id_team not between", value1, value2, "idTeam");
            return (Criteria) this;
        }

        public Criteria andRankIsNull() {
            addCriterion("rank is null");
            return (Criteria) this;
        }

        public Criteria andRankIsNotNull() {
            addCriterion("rank is not null");
            return (Criteria) this;
        }

        public Criteria andRankEqualTo(String value) {
            addCriterion("rank =", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotEqualTo(String value) {
            addCriterion("rank <>", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThan(String value) {
            addCriterion("rank >", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThanOrEqualTo(String value) {
            addCriterion("rank >=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThan(String value) {
            addCriterion("rank <", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThanOrEqualTo(String value) {
            addCriterion("rank <=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLike(String value) {
            addCriterion("rank like", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotLike(String value) {
            addCriterion("rank not like", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankIn(List<String> values) {
            addCriterion("rank in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotIn(List<String> values) {
            addCriterion("rank not in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankBetween(String value1, String value2) {
            addCriterion("rank between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotBetween(String value1, String value2) {
            addCriterion("rank not between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andMbileIsNull() {
            addCriterion("mbile is null");
            return (Criteria) this;
        }

        public Criteria andMbileIsNotNull() {
            addCriterion("mbile is not null");
            return (Criteria) this;
        }

        public Criteria andMbileEqualTo(String value) {
            addCriterion("mbile =", value, "mbile");
            return (Criteria) this;
        }

        public Criteria andMbileNotEqualTo(String value) {
            addCriterion("mbile <>", value, "mbile");
            return (Criteria) this;
        }

        public Criteria andMbileGreaterThan(String value) {
            addCriterion("mbile >", value, "mbile");
            return (Criteria) this;
        }

        public Criteria andMbileGreaterThanOrEqualTo(String value) {
            addCriterion("mbile >=", value, "mbile");
            return (Criteria) this;
        }

        public Criteria andMbileLessThan(String value) {
            addCriterion("mbile <", value, "mbile");
            return (Criteria) this;
        }

        public Criteria andMbileLessThanOrEqualTo(String value) {
            addCriterion("mbile <=", value, "mbile");
            return (Criteria) this;
        }

        public Criteria andMbileLike(String value) {
            addCriterion("mbile like", value, "mbile");
            return (Criteria) this;
        }

        public Criteria andMbileNotLike(String value) {
            addCriterion("mbile not like", value, "mbile");
            return (Criteria) this;
        }

        public Criteria andMbileIn(List<String> values) {
            addCriterion("mbile in", values, "mbile");
            return (Criteria) this;
        }

        public Criteria andMbileNotIn(List<String> values) {
            addCriterion("mbile not in", values, "mbile");
            return (Criteria) this;
        }

        public Criteria andMbileBetween(String value1, String value2) {
            addCriterion("mbile between", value1, value2, "mbile");
            return (Criteria) this;
        }

        public Criteria andMbileNotBetween(String value1, String value2) {
            addCriterion("mbile not between", value1, value2, "mbile");
            return (Criteria) this;
        }

        public Criteria andEMailIsNull() {
            addCriterion("e_mail is null");
            return (Criteria) this;
        }

        public Criteria andEMailIsNotNull() {
            addCriterion("e_mail is not null");
            return (Criteria) this;
        }

        public Criteria andEMailEqualTo(String value) {
            addCriterion("e_mail =", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailNotEqualTo(String value) {
            addCriterion("e_mail <>", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailGreaterThan(String value) {
            addCriterion("e_mail >", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailGreaterThanOrEqualTo(String value) {
            addCriterion("e_mail >=", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailLessThan(String value) {
            addCriterion("e_mail <", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailLessThanOrEqualTo(String value) {
            addCriterion("e_mail <=", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailLike(String value) {
            addCriterion("e_mail like", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailNotLike(String value) {
            addCriterion("e_mail not like", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailIn(List<String> values) {
            addCriterion("e_mail in", values, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailNotIn(List<String> values) {
            addCriterion("e_mail not in", values, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailBetween(String value1, String value2) {
            addCriterion("e_mail between", value1, value2, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailNotBetween(String value1, String value2) {
            addCriterion("e_mail not between", value1, value2, "eMail");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated do_not_delete_during_merge Mon Oct 26 09:42:08 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}