package skyline.platform.repository.model;

public class THrmBranchDept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_branch_dept.branch
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    private String branch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_branch_dept.id_dept
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    private String idDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_branch_dept.name_dept
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    private String nameDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_branch_dept.describe
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_branch_dept.id_manage
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    private String idManage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_branch_dept.category
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    private String category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_branch_dept.branch
     *
     * @return the value of t_hrm_branch_dept.branch
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public String getBranch() {
        return branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_branch_dept.branch
     *
     * @param branch the value for t_hrm_branch_dept.branch
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public void setBranch(String branch) {
        this.branch = branch == null ? null : branch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_branch_dept.id_dept
     *
     * @return the value of t_hrm_branch_dept.id_dept
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public String getIdDept() {
        return idDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_branch_dept.id_dept
     *
     * @param idDept the value for t_hrm_branch_dept.id_dept
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public void setIdDept(String idDept) {
        this.idDept = idDept == null ? null : idDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_branch_dept.name_dept
     *
     * @return the value of t_hrm_branch_dept.name_dept
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public String getNameDept() {
        return nameDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_branch_dept.name_dept
     *
     * @param nameDept the value for t_hrm_branch_dept.name_dept
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public void setNameDept(String nameDept) {
        this.nameDept = nameDept == null ? null : nameDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_branch_dept.describe
     *
     * @return the value of t_hrm_branch_dept.describe
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_branch_dept.describe
     *
     * @param describe the value for t_hrm_branch_dept.describe
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_branch_dept.id_manage
     *
     * @return the value of t_hrm_branch_dept.id_manage
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public String getIdManage() {
        return idManage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_branch_dept.id_manage
     *
     * @param idManage the value for t_hrm_branch_dept.id_manage
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public void setIdManage(String idManage) {
        this.idManage = idManage == null ? null : idManage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_branch_dept.category
     *
     * @return the value of t_hrm_branch_dept.category
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_branch_dept.category
     *
     * @param category the value for t_hrm_branch_dept.category
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }
}