package skyline.platform.repository.model;

public class THrmNewsmodel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_newsmodel.id
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_newsmodel.model_name
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    private String modelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_newsmodel.model_creadTime
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    private String modelCreadtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_newsmodel.central_department_id
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    private String centralDepartmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_newsmodel.isenable
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    private String isenable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_newsmodel.id
     *
     * @return the value of t_hrm_newsmodel.id
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_newsmodel.id
     *
     * @param id the value for t_hrm_newsmodel.id
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_newsmodel.model_name
     *
     * @return the value of t_hrm_newsmodel.model_name
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_newsmodel.model_name
     *
     * @param modelName the value for t_hrm_newsmodel.model_name
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public void setModelName(String modelName) {
        this.modelName = modelName == null ? null : modelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_newsmodel.model_creadTime
     *
     * @return the value of t_hrm_newsmodel.model_creadTime
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public String getModelCreadtime() {
        return modelCreadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_newsmodel.model_creadTime
     *
     * @param modelCreadtime the value for t_hrm_newsmodel.model_creadTime
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public void setModelCreadtime(String modelCreadtime) {
        this.modelCreadtime = modelCreadtime == null ? null : modelCreadtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_newsmodel.central_department_id
     *
     * @return the value of t_hrm_newsmodel.central_department_id
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public String getCentralDepartmentId() {
        return centralDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_newsmodel.central_department_id
     *
     * @param centralDepartmentId the value for t_hrm_newsmodel.central_department_id
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public void setCentralDepartmentId(String centralDepartmentId) {
        this.centralDepartmentId = centralDepartmentId == null ? null : centralDepartmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_newsmodel.isenable
     *
     * @return the value of t_hrm_newsmodel.isenable
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public String getIsenable() {
        return isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_newsmodel.isenable
     *
     * @param isenable the value for t_hrm_newsmodel.isenable
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public void setIsenable(String isenable) {
        this.isenable = isenable == null ? null : isenable.trim();
    }
}