package skyline.platform.repository.model;

public class THrmNewsWithBLOBs extends THrmNews {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_news.news_content
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String newsContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_news.news_img
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private byte[] newsImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_news.news_img_flag
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private byte[] newsImgFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_news.news_attachment
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private byte[] newsAttachment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_news.model_id
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private byte[] modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_news.central_department_id
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private byte[] centralDepartmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_news.news_topTime
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private byte[] newsToptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_news.news_createdTime
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private byte[] newsCreatedtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_news.news_content
     *
     * @return the value of t_hrm_news.news_content
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getNewsContent() {
        return newsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_news.news_content
     *
     * @param newsContent the value for t_hrm_news.news_content
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setNewsContent(String newsContent) {
        this.newsContent = newsContent == null ? null : newsContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_news.news_img
     *
     * @return the value of t_hrm_news.news_img
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public byte[] getNewsImg() {
        return newsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_news.news_img
     *
     * @param newsImg the value for t_hrm_news.news_img
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setNewsImg(byte[] newsImg) {
        this.newsImg = newsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_news.news_img_flag
     *
     * @return the value of t_hrm_news.news_img_flag
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public byte[] getNewsImgFlag() {
        return newsImgFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_news.news_img_flag
     *
     * @param newsImgFlag the value for t_hrm_news.news_img_flag
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setNewsImgFlag(byte[] newsImgFlag) {
        this.newsImgFlag = newsImgFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_news.news_attachment
     *
     * @return the value of t_hrm_news.news_attachment
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public byte[] getNewsAttachment() {
        return newsAttachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_news.news_attachment
     *
     * @param newsAttachment the value for t_hrm_news.news_attachment
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setNewsAttachment(byte[] newsAttachment) {
        this.newsAttachment = newsAttachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_news.model_id
     *
     * @return the value of t_hrm_news.model_id
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public byte[] getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_news.model_id
     *
     * @param modelId the value for t_hrm_news.model_id
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setModelId(byte[] modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_news.central_department_id
     *
     * @return the value of t_hrm_news.central_department_id
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public byte[] getCentralDepartmentId() {
        return centralDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_news.central_department_id
     *
     * @param centralDepartmentId the value for t_hrm_news.central_department_id
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setCentralDepartmentId(byte[] centralDepartmentId) {
        this.centralDepartmentId = centralDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_news.news_topTime
     *
     * @return the value of t_hrm_news.news_topTime
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public byte[] getNewsToptime() {
        return newsToptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_news.news_topTime
     *
     * @param newsToptime the value for t_hrm_news.news_topTime
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setNewsToptime(byte[] newsToptime) {
        this.newsToptime = newsToptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_news.news_createdTime
     *
     * @return the value of t_hrm_news.news_createdTime
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public byte[] getNewsCreatedtime() {
        return newsCreatedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_news.news_createdTime
     *
     * @param newsCreatedtime the value for t_hrm_news.news_createdTime
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setNewsCreatedtime(byte[] newsCreatedtime) {
        this.newsCreatedtime = newsCreatedtime;
    }
}