package skyline.platform.repository.model;

public class THrmImages {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_images.id
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_images.img
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_images.position
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_images.dept_id
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    private String deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_images.title
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_images.isenable
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    private String isenable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_images.createdTime
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    private String createdtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_images.id
     *
     * @return the value of t_hrm_images.id
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_images.id
     *
     * @param id the value for t_hrm_images.id
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_images.img
     *
     * @return the value of t_hrm_images.img
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_images.img
     *
     * @param img the value for t_hrm_images.img
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_images.position
     *
     * @return the value of t_hrm_images.position
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_images.position
     *
     * @param position the value for t_hrm_images.position
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_images.dept_id
     *
     * @return the value of t_hrm_images.dept_id
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_images.dept_id
     *
     * @param deptId the value for t_hrm_images.dept_id
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_images.title
     *
     * @return the value of t_hrm_images.title
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_images.title
     *
     * @param title the value for t_hrm_images.title
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_images.isenable
     *
     * @return the value of t_hrm_images.isenable
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public String getIsenable() {
        return isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_images.isenable
     *
     * @param isenable the value for t_hrm_images.isenable
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public void setIsenable(String isenable) {
        this.isenable = isenable == null ? null : isenable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_images.createdTime
     *
     * @return the value of t_hrm_images.createdTime
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public String getCreatedtime() {
        return createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_images.createdTime
     *
     * @param createdtime the value for t_hrm_images.createdTime
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public void setCreatedtime(String createdtime) {
        this.createdtime = createdtime == null ? null : createdtime.trim();
    }
}