package skyline.platform.repository.model;

public class THrmParameter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_parameter.lb
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    private String lb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_parameter.dm
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    private String dm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_parameter.mc
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    private String mc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_parameter.lb
     *
     * @return the value of t_hrm_parameter.lb
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public String getLb() {
        return lb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_parameter.lb
     *
     * @param lb the value for t_hrm_parameter.lb
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public void setLb(String lb) {
        this.lb = lb == null ? null : lb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_parameter.dm
     *
     * @return the value of t_hrm_parameter.dm
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public String getDm() {
        return dm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_parameter.dm
     *
     * @param dm the value for t_hrm_parameter.dm
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public void setDm(String dm) {
        this.dm = dm == null ? null : dm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_parameter.mc
     *
     * @return the value of t_hrm_parameter.mc
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public String getMc() {
        return mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_parameter.mc
     *
     * @param mc the value for t_hrm_parameter.mc
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    public void setMc(String mc) {
        this.mc = mc == null ? null : mc.trim();
    }
}