package skyline.platform.repository.model;

public class THrmStaffBaseInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_base_info.ser_no
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String serNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_base_info.ser_name
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String serName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_base_info.ser_pwd
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String serPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_base_info.id_dept
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String idDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_base_info.id_team
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String idTeam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_base_info.rank
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_base_info.mbile
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String mbile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_base_info.e_mail
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String eMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_staff_base_info.status
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_base_info.ser_no
     *
     * @return the value of t_hrm_staff_base_info.ser_no
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getSerNo() {
        return serNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_base_info.ser_no
     *
     * @param serNo the value for t_hrm_staff_base_info.ser_no
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setSerNo(String serNo) {
        this.serNo = serNo == null ? null : serNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_base_info.ser_name
     *
     * @return the value of t_hrm_staff_base_info.ser_name
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getSerName() {
        return serName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_base_info.ser_name
     *
     * @param serName the value for t_hrm_staff_base_info.ser_name
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setSerName(String serName) {
        this.serName = serName == null ? null : serName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_base_info.ser_pwd
     *
     * @return the value of t_hrm_staff_base_info.ser_pwd
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getSerPwd() {
        return serPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_base_info.ser_pwd
     *
     * @param serPwd the value for t_hrm_staff_base_info.ser_pwd
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setSerPwd(String serPwd) {
        this.serPwd = serPwd == null ? null : serPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_base_info.id_dept
     *
     * @return the value of t_hrm_staff_base_info.id_dept
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getIdDept() {
        return idDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_base_info.id_dept
     *
     * @param idDept the value for t_hrm_staff_base_info.id_dept
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setIdDept(String idDept) {
        this.idDept = idDept == null ? null : idDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_base_info.id_team
     *
     * @return the value of t_hrm_staff_base_info.id_team
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getIdTeam() {
        return idTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_base_info.id_team
     *
     * @param idTeam the value for t_hrm_staff_base_info.id_team
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setIdTeam(String idTeam) {
        this.idTeam = idTeam == null ? null : idTeam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_base_info.rank
     *
     * @return the value of t_hrm_staff_base_info.rank
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_base_info.rank
     *
     * @param rank the value for t_hrm_staff_base_info.rank
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setRank(String rank) {
        this.rank = rank == null ? null : rank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_base_info.mbile
     *
     * @return the value of t_hrm_staff_base_info.mbile
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getMbile() {
        return mbile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_base_info.mbile
     *
     * @param mbile the value for t_hrm_staff_base_info.mbile
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setMbile(String mbile) {
        this.mbile = mbile == null ? null : mbile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_base_info.e_mail
     *
     * @return the value of t_hrm_staff_base_info.e_mail
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String geteMail() {
        return eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_base_info.e_mail
     *
     * @param eMail the value for t_hrm_staff_base_info.e_mail
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void seteMail(String eMail) {
        this.eMail = eMail == null ? null : eMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_staff_base_info.status
     *
     * @return the value of t_hrm_staff_base_info.status
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_staff_base_info.status
     *
     * @param status the value for t_hrm_staff_base_info.status
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}