package skyline.platform.repository.model;

public class THrmNewsmodelWithBLOBs extends THrmNewsmodel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_newsmodel.model_name
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private byte[] modelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_newsmodel.model_creadTime
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private byte[] modelCreadtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_newsmodel.central_department_id
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private byte[] centralDepartmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_newsmodel.model_name
     *
     * @return the value of t_hrm_newsmodel.model_name
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public byte[] getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_newsmodel.model_name
     *
     * @param modelName the value for t_hrm_newsmodel.model_name
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setModelName(byte[] modelName) {
        this.modelName = modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_newsmodel.model_creadTime
     *
     * @return the value of t_hrm_newsmodel.model_creadTime
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public byte[] getModelCreadtime() {
        return modelCreadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_newsmodel.model_creadTime
     *
     * @param modelCreadtime the value for t_hrm_newsmodel.model_creadTime
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setModelCreadtime(byte[] modelCreadtime) {
        this.modelCreadtime = modelCreadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_newsmodel.central_department_id
     *
     * @return the value of t_hrm_newsmodel.central_department_id
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public byte[] getCentralDepartmentId() {
        return centralDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_newsmodel.central_department_id
     *
     * @param centralDepartmentId the value for t_hrm_newsmodel.central_department_id
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setCentralDepartmentId(byte[] centralDepartmentId) {
        this.centralDepartmentId = centralDepartmentId;
    }
}