package skyline.platform.repository.model;

public class THrmNewsmodel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_newsmodel.id
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_newsmodel.isenable
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    private String isenable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_newsmodel.id
     *
     * @return the value of t_hrm_newsmodel.id
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_newsmodel.id
     *
     * @param id the value for t_hrm_newsmodel.id
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_newsmodel.isenable
     *
     * @return the value of t_hrm_newsmodel.isenable
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public String getIsenable() {
        return isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_newsmodel.isenable
     *
     * @param isenable the value for t_hrm_newsmodel.isenable
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    public void setIsenable(String isenable) {
        this.isenable = isenable == null ? null : isenable.trim();
    }
}