package skyline.platform.repository.model.model_show;

public class MyTHrmNewsAndDept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_news.id
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_news.news_title
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    private String newsTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_news.news_img
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    private String newsImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_news.news_img_flag
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    private String newsImgFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_news.news_attachment
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    private String newsAttachment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_news.model_id
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    private String modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_news.central_department_id
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    private String centralDepartmentId;

    private String departmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_news.news_istop
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    private String newsIstop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_news.isenable
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    private String isenable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hrm_news.news_createdTime
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    private String newsCreatedtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_news.id
     *
     * @return the value of t_hrm_news.id
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_news.id
     *
     * @param id the value for t_hrm_news.id
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_news.news_title
     *
     * @return the value of t_hrm_news.news_title
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public String getNewsTitle() {
        return newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_news.news_title
     *
     * @param newsTitle the value for t_hrm_news.news_title
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle == null ? null : newsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_news.news_img
     *
     * @return the value of t_hrm_news.news_img
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public String getNewsImg() {
        return newsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_news.news_img
     *
     * @param newsImg the value for t_hrm_news.news_img
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public void setNewsImg(String newsImg) {
        this.newsImg = newsImg == null ? null : newsImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_news.news_img_flag
     *
     * @return the value of t_hrm_news.news_img_flag
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public String getNewsImgFlag() {
        return newsImgFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_news.news_img_flag
     *
     * @param newsImgFlag the value for t_hrm_news.news_img_flag
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public void setNewsImgFlag(String newsImgFlag) {
        this.newsImgFlag = newsImgFlag == null ? null : newsImgFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_news.news_attachment
     *
     * @return the value of t_hrm_news.news_attachment
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public String getNewsAttachment() {
        return newsAttachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_news.news_attachment
     *
     * @param newsAttachment the value for t_hrm_news.news_attachment
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public void setNewsAttachment(String newsAttachment) {
        this.newsAttachment = newsAttachment == null ? null : newsAttachment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_news.model_id
     *
     * @return the value of t_hrm_news.model_id
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public String getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_news.model_id
     *
     * @param modelId the value for t_hrm_news.model_id
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public void setModelId(String modelId) {
        this.modelId = modelId == null ? null : modelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_news.central_department_id
     *
     * @return the value of t_hrm_news.central_department_id
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public String getCentralDepartmentId() {
        return centralDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_news.central_department_id
     *
     * @param centralDepartmentId the value for t_hrm_news.central_department_id
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public void setCentralDepartmentId(String centralDepartmentId) {
        this.centralDepartmentId = centralDepartmentId == null ? null : centralDepartmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_news.news_istop
     *
     * @return the value of t_hrm_news.news_istop
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public String getNewsIstop() {
        return newsIstop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_news.news_istop
     *
     * @param newsIstop the value for t_hrm_news.news_istop
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public void setNewsIstop(String newsIstop) {
        this.newsIstop = newsIstop == null ? null : newsIstop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_news.isenable
     *
     * @return the value of t_hrm_news.isenable
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public String getIsenable() {
        return isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_news.isenable
     *
     * @param isenable the value for t_hrm_news.isenable
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public void setIsenable(String isenable) {
        this.isenable = isenable == null ? null : isenable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hrm_news.news_createdTime
     *
     * @return the value of t_hrm_news.news_createdTime
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public String getNewsCreatedtime() {
        return newsCreatedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hrm_news.news_createdTime
     *
     * @param newsCreatedtime the value for t_hrm_news.news_createdTime
     *
     * @mbggenerated Mon Oct 26 09:42:08 CST 2015
     */
    public void setNewsCreatedtime(String newsCreatedtime) {
        this.newsCreatedtime = newsCreatedtime == null ? null : newsCreatedtime.trim();
    }

    public String getDepartmentName() {
        return departmentName;
    }

    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }
}