package skyline.platform.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import skyline.platform.repository.model.THrmNewsmodel;
import skyline.platform.repository.model.THrmNewsmodelExample;

public interface THrmNewsmodelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_newsmodel
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int countByExample(THrmNewsmodelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_newsmodel
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int deleteByExample(THrmNewsmodelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_newsmodel
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_newsmodel
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int insert(THrmNewsmodel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_newsmodel
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int insertSelective(THrmNewsmodel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_newsmodel
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    List<THrmNewsmodel> selectByExample(THrmNewsmodelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_newsmodel
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    THrmNewsmodel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_newsmodel
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int updateByExampleSelective(@Param("record") THrmNewsmodel record, @Param("example") THrmNewsmodelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_newsmodel
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int updateByExample(@Param("record") THrmNewsmodel record, @Param("example") THrmNewsmodelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_newsmodel
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int updateByPrimaryKeySelective(THrmNewsmodel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_newsmodel
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int updateByPrimaryKey(THrmNewsmodel record);
}