package skyline.platform.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import skyline.platform.repository.model.THrmStaffBaseInfo;
import skyline.platform.repository.model.THrmStaffBaseInfoExample;

public interface THrmStaffBaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int countByExample(THrmStaffBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int deleteByExample(THrmStaffBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int deleteByPrimaryKey(String serNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int insert(THrmStaffBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int insertSelective(THrmStaffBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    List<THrmStaffBaseInfo> selectByExample(THrmStaffBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    THrmStaffBaseInfo selectByPrimaryKey(String serNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int updateByExampleSelective(@Param("record") THrmStaffBaseInfo record, @Param("example") THrmStaffBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int updateByExample(@Param("record") THrmStaffBaseInfo record, @Param("example") THrmStaffBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int updateByPrimaryKeySelective(THrmStaffBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_base_info
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int updateByPrimaryKey(THrmStaffBaseInfo record);
}