package skyline.platform.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import skyline.platform.repository.model.THrmBranch;
import skyline.platform.repository.model.THrmBranchExample;

public interface THrmBranchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_branch
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    int countByExample(THrmBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_branch
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    int deleteByExample(THrmBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_branch
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    int insert(THrmBranch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_branch
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    int insertSelective(THrmBranch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_branch
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    List<THrmBranch> selectByExample(THrmBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_branch
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") THrmBranch record, @Param("example") THrmBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_branch
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    int updateByExample(@Param("record") THrmBranch record, @Param("example") THrmBranchExample example);
}