package skyline.platform.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import skyline.platform.repository.model.THrmStaffPermission;
import skyline.platform.repository.model.THrmStaffPermissionExample;

public interface THrmStaffPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_permission
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int countByExample(THrmStaffPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_permission
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int deleteByExample(THrmStaffPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_permission
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int insert(THrmStaffPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_permission
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int insertSelective(THrmStaffPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_permission
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    List<THrmStaffPermission> selectByExample(THrmStaffPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_permission
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int updateByExampleSelective(@Param("record") THrmStaffPermission record, @Param("example") THrmStaffPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_staff_permission
     *
     * @mbggenerated Thu Oct 22 15:53:55 CST 2015
     */
    int updateByExample(@Param("record") THrmStaffPermission record, @Param("example") THrmStaffPermissionExample example);
}