package skyline.platform.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import skyline.platform.repository.model.THrmNewsmodel;
import skyline.platform.repository.model.THrmNewsmodelExample;
import skyline.platform.repository.model.THrmNewsmodelWithBLOBs;

public interface THrmNewsmodelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_newsmodel
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    int countByExample(THrmNewsmodelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_newsmodel
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    int deleteByExample(THrmNewsmodelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_newsmodel
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    int insert(THrmNewsmodelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_newsmodel
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    int insertSelective(THrmNewsmodelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_newsmodel
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    List<THrmNewsmodelWithBLOBs> selectByExampleWithBLOBs(THrmNewsmodelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_newsmodel
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    List<THrmNewsmodel> selectByExample(THrmNewsmodelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_newsmodel
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") THrmNewsmodelWithBLOBs record, @Param("example") THrmNewsmodelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_newsmodel
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") THrmNewsmodelWithBLOBs record, @Param("example") THrmNewsmodelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_newsmodel
     *
     * @mbggenerated Wed Oct 21 20:16:14 CST 2015
     */
    int updateByExample(@Param("record") THrmNewsmodel record, @Param("example") THrmNewsmodelExample example);
}