package skyline.platform.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import skyline.platform.repository.model.THrmImages;
import skyline.platform.repository.model.THrmImagesExample;

public interface THrmImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_images
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    int countByExample(THrmImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_images
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    int deleteByExample(THrmImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_images
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_images
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    int insert(THrmImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_images
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    int insertSelective(THrmImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_images
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    List<THrmImages> selectByExample(THrmImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_images
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    THrmImages selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_images
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    int updateByExampleSelective(@Param("record") THrmImages record, @Param("example") THrmImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_images
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    int updateByExample(@Param("record") THrmImages record, @Param("example") THrmImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_images
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    int updateByPrimaryKeySelective(THrmImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_images
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    int updateByPrimaryKey(THrmImages record);
}