package skyline.platform.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import skyline.platform.repository.model.THrmNews;
import skyline.platform.repository.model.THrmNewsExample;

public interface THrmNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    int countByExample(THrmNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    int deleteByExample(THrmNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    int insert(THrmNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    int insertSelective(THrmNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    List<THrmNews> selectByExampleWithBLOBs(THrmNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    List<THrmNews> selectByExample(THrmNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    THrmNews selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    int updateByExampleSelective(@Param("record") THrmNews record, @Param("example") THrmNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") THrmNews record, @Param("example") THrmNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    int updateByExample(@Param("record") THrmNews record, @Param("example") THrmNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    int updateByPrimaryKeySelective(THrmNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(THrmNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hrm_news
     *
     * @mbggenerated Tue Oct 27 20:45:26 CST 2015
     */
    int updateByPrimaryKey(THrmNews record);
}